DROP TABLE CLASSIFICACAO;
DROP SEQUENCE SEQ_CLASSIFICACAO;
CREATE SEQUENCE SEQ_CLASSIFICACAO
NOCACHE;
CREATE TABLE CLASSIFICACAO (
    ID INTEGER PRIMARY KEY,
    VALOR VARCHAR2(20) NOT NULL);
CREATE OR REPLACE TRIGGER CLASSIFICACAO_TG
BEFORE INSERT ON CLASSIFICACAO
FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_CLASSIFICACAO.NEXTVAL;
END;
/