DROP TABLE AMOSTRAS;
DROP SEQUENCE SEQ_AMOSTRAS;
CREATE SEQUENCE SEQ_AMOSTRAS
NOCACHE;
CREATE TABLE AMOSTRAS (
    ID INTEGER PRIMARY KEY,
    MP10 INTEGER NOT NULL,
    MP2_5 INTEGER NOT NULL,
    O3 INTEGER NOT NULL,
    CO INTEGER NOT NULL,
    NO2 INTEGER NOT NULL,
    SO2 INTEGER NOT NULL);
CREATE OR REPLACE TRIGGER GERADOR_ID_AMOSTRAS
BEFORE INSERT ON AMOSTRAS
FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_AMOSTRAS.NEXTVAL;
END;
/
