DROP TABLE AMOSTRAS;
DROP SEQUENCE SEQ_AMOSTRAS;
CREATE SEQUENCE SEQ_AMOSTRAS
NOCACHE;
CREATE TABLE AMOSTRAS (
    ID INTEGER PRIMARY KEY,
    MP10 FLOAT NOT NULL,
    MP2_5 FLOAT NOT NULL,
    O3 FLOAT NOT NULL,
    CO FLOAT NOT NULL,
    NO2 FLOAT NOT NULL,
    SO2 FLOAT NOT NULL);
CREATE OR REPLACE TRIGGER GERADOR_ID_AMOSTRAS
BEFORE INSERT ON AMOSTRAS
FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_AMOSTRAS.NEXTVAL;
END;
/
